language: java
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - qrioflat@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

jdk:
  - openjdk11

services:
  - postgresql

before_install:
  - chmod +x mvnw
  - psql -c 'create database warranty;' -U postgres
