version: "3.9"
services:
  db_warranty:
    image: postgres
    container_name: db_warranty
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=warranty
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - /docker/volums/warranty/db/data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
  warranty:
    image: warranty
    container_name: warranty
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_warranty:5432/warranty
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db_warranty
    restart: always
